services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portofolio-wisnu
    restart: unless-stopped
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: ['pnpm', 'next', 'start']
